# Generated by GPT-5.2 (Codex CLI) on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_validator",
            field=models.BooleanField(default=False, verbose_name="validador"),
        ),
    ]

