# Generated by Django 5.0 on 2026-03-13 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0013_add_assessment_environment_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='generating', max_length=20, verbose_name='status')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='reports/%Y/%m/', verbose_name='arquivo PDF')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('generation_time_seconds', models.FloatField(blank=True, help_text='Tempo total de geração do PDF em segundos', null=True, verbose_name='tempo de geração (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assessments.riskassessment', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assessment', '-created_at'], name='reports_rep_assessm_1c5f47_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='reports_rep_status_65d620_idx'),
        ),
    ]
