# Generated by Django 5.2.11 on 2026-02-17 16:20

import assessments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_offline_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='client_ref',
            field=models.UUIDField(blank=True, null=True, verbose_name='client_ref'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(max_length=500, upload_to=assessments.models.evidence_upload_to, verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='client_ref',
            field=models.UUIDField(blank=True, null=True, verbose_name='client_ref'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('captured', 'Capturada'), ('submitted', 'Enviada'), ('in_review', 'Em revisão'), ('closed', 'Encerrada')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('assessment', 'client_ref'), name='uq_evidence_client_ref_assessment'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(fields=('created_by', 'client_ref'), name='uq_assessment_client_ref_user'),
        ),
    ]
