# Generated by GPT-5.2 (Codex CLI) on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_client_ref_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinferenceresult",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="erro"),
        ),
        migrations.AddField(
            model_name="aiinferenceresult",
            name="model_version",
            field=models.CharField(blank=True, max_length=100, verbose_name="versÃ£o do modelo"),
        ),
        migrations.AddField(
            model_name="aiinferenceresult",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pendente"), ("succeeded", "ConcluÃ­do"), ("failed", "Falhou")],
                default="pending",
                max_length=20,
            ),
        ),
    ]

