# Generated by GPT-5.2 (Codex CLI) on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_ai_inference_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanvalidationdecision",
            name="override",
            field=models.JSONField(blank=True, default=dict, verbose_name="override"),
        ),
        migrations.AddField(
            model_name="humanvalidationdecision",
            name="reject_reason",
            field=models.TextField(blank=True, verbose_name="motivo da rejeiÃ§Ã£o"),
        ),
    ]

