# Generated by Django 5.2.11 on 2026-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_environment_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evidence',
            name='uq_evidence_client_ref_assessment',
        ),
        migrations.RemoveConstraint(
            model_name='riskassessment',
            name='uq_assessment_client_ref_user',
        ),
        migrations.RemoveField(
            model_name='aiinferenceresult',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='aiinferenceresult',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='aiinferenceresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='captured_at',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='client_ref',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='humanvalidationdecision',
            name='override',
        ),
        migrations.RemoveField(
            model_name='humanvalidationdecision',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='client_ref',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='environment',
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('in_review', 'Em revisão'), ('closed', 'Encerrada')], default='draft', max_length=20),
        ),
    ]
