# Generated by Django 5.2.12 on 2026-03-12 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_evidence_captured_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisado por IA em'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='capturado em'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finalizado em'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='human_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validado por humano em'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='status_change_reason',
            field=models.TextField(blank=True, verbose_name='motivo da mudança'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última mudança de status em'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sincronizado em'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('captured', 'Capturado'), ('synced', 'Sincronizado'), ('ai_reviewed', 'Revisado por IA'), ('human_validated', 'Validado por Humano'), ('finalized', 'Finalizado'), ('error', 'Erro')], default='draft', max_length=20),
        ),
    ]
